/**
 * Articles hidden from the public listing + nav because they are duplicate
 * "stub" versions of a fuller essay (see docs/content-audit.md, §3). Hiding
 * here removes them from the reader experience immediately, with no admin
 * action. They can also be formally unpublished from the duplicate tool.
 */
export const HIDDEN_SLUGS = new Set<string>([
  "justice-not-political",        // → justice-is-not-political-it-is-theological
  "poor-not-ministry",            // → the-poor-are-not-a-ministry-category-test-of-the-church
  "your-city-is-mission-field",   // → your-city-is-your-mission-field-biblical-theology-of-place
  "consistent-ethic-life",        // → consistent-pro-life-ethic
]);

/**
 * PCN-import stubs retired by the 2026 voice audit (docs/VOICE-AUDIT-TOTAL.md):
 * published posts under 200 words that were placeholders describing an essay
 * never written, not short essays. Unpublished in content-data.json (and via
 * scripts/unpublish-stubs.mjs against the live DB); hidden here so no listing
 * surface offers a reader a phantom article while old DB rows linger.
 */
export const STUB_SLUGS: readonly string[] = [
  "anxiety-perfectionism-pastor-breaking-cycle",
  "art-of-saying-no-without-guilt",
  "atonement-more-than-one-model",
  "beatitudes-actually-promising",
  "before-launch-ministry-ask-other-church",
  "building-leadership-team",
  "burnout-nobody-talks-about",
  "children-poverty-prophetic-indictment",
  "church-closures-outpacing-plants",
  "church-comfort-inequality",
  "church-credibility-problem",
  "church-fathers-not-boring",
  "church-megaproject-widows-mite",
  "church-mental-health-justice",
  "church-must-speak-housing",
  "church-needs-you-healthy-not-busy",
  "church-political-brand-step-back",
  "church-response-poverty-charity",
  "church-response-to-culture",
  "church-split-surviving-learning-forward",
  "church-wealth-world-poverty",
  "city-wide-church-together",
  "collaboration-across-denominations",
  "color-blindness-not-virtue",
  "complicity-not-innocence",
  "conflict-is-not-failure",
  "courage-to-be-different",
  "danger-pastoral-isolation",
  "delegation-is-not-weakness",
  "difference-tired-and-done",
  "earth-is-lords",
  "eighty-percent-churches-plateaued",
  "eschatology-matters-end-shapes-now",
  "exodus-demands-church-today",
  "finding-your-barnabas",
  "five-biggest-mistakes-new-pastors",
  "five-sermon-habits-shrinking-faith",
  "give-feedback-changes-behavior",
  "global-church-is-your-church",
  "good-samaritan-arguing",
  "greek-original-language-matters",
  "healthy-pastor-referral-network",
  "hidden-pain-successful-pastor",
  "holy-spirit-not-feeling",
  "hope-of-resurrection",
  "hospitality-not-optional",
  "imago-dei-means-more",
  "incarnation-changes-everything",
  "interior-life-of-pastor",
  "justice-without-love-ideology",
  "kingdom-of-god-not-what-you-think",
  "lead-church-decline-without-losing-hope",
  "lead-through-church-crisis",
  "lead-when-trust-institutions-low",
  "learned-unity-pastoring-across-cultures",
  "loneliness-of-leadership",
  "metrics-tell-church-healthy",
  "micah-6-8-demands",
  "mishpat-tsedaqah",
  "mission-is-not-optional",
  "mission-sending-culture-never-sent",
  "most-dangerous-person-church-staff",
  "most-prophetic-live-differently",
  "national-pastors-redefining-missionary",
  "not-persecuted-seduced-crisis-american-christianity",
  "not-your-churchs-attendance-numbers",
  "okay-to-see-counselor",
  "pastor-politically-divided-gospel-central",
  "pastoral-care-wealthy-congregant",
  "pastors-authority-relational",
  "pastors-kids-watching-what-seeing",
  "personal-board-accountability",
  "prayer-is-not-optional",
  "preach-same-gospel-different-people",
  "preaching-to-room-not-there-yet",
  "present-at-home-mind-never-leaves",
  "prophetic-pastor",
  "prophetic-tradition-economic-justice",
  "prophets-expelled-sanctuary",
  "protecting-marriage-ministry-demands",
  "psalms-as-prayer-not-poetry",
  "reaching-rich-comfortable",
  "repentance-and-renewal",
  "revitalize-or-replant",
  "ruth-gleaning-laws",
  "sabbath-is-resistance",
  "sabbath-isnt-optional",
  "sabbatical-why-church-should-require",
  "scandals-teaching-accountability",
  "scripture-meditation",
  "sin-not-just-what-you-do",
  "slow-burn-ministry-exhaustion",
  "solidarity-theological-virtue",
  "spiritual-disciplines-for-pastors",
  "spouse-wishes-knew-parsonage",
  "staff-culture-no-burnout",
  "stop-performing-start-pastoring",
  "stopped-competing-church-across-town",
  "stranger-at-gate",
  "talk-global-missions-moves-congregation",
  "talk-politics-pulpit-without-destroying",
  "the-examined-life",
  "the-long-arc",
  "the-monster-in-the-mirror",
  "theology-of-repair",
  "three-small-churches-coplanted",
  "unity-without-uniformity",
  "unreached-people-groups-closest-to-you",
  "vision-without-community-fantasy",
  "vulnerable-people-not-in-pews",
  "weight-of-what-you-cant-say",
  "what-jubilee-means",
  "what-we-owe-generations",
  "when-fire-someone-with-integrity",
  "when-god-bless-america-replaces-thy-kingdom-come",
  "when-man-pulpit-falling-apart",
  "when-preaching-gets-stale",
  "when-shepherd-needs-shepherding",
  "white-churches-wrong-about-diversity",
  "why-pastors-quit-and-how-to-stay",
  "why-poverty-political",
  "widow-orphan-stranger",
  "you-are-not-the-exception",
  "young-adults-coming-back-church",
  "your-marriage-is-ministry-too",
];
for (const s of STUB_SLUGS) HIDDEN_SLUGS.add(s);
