/**
 * Renders a study-guide leader resource suite from
 * client/public/studyguides/<slug>.json at /studyguides/:slug. Tabs across
 * the suite (Leader's Guide, Participant Handout, Facilitator Script,
 * Reference, Promo Kit), with email-gated PDF downloads of the Leader's Guide
 * and Participant Handout generated by scripts/build-pdfs.mjs.
 */
import { useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import Layout from "@/components/Layout";
import { SEOMeta } from "@/components/SEOMeta";
import GatedDownload from "@/components/GatedDownload";

const wrap = { maxWidth: "var(--w-default)", margin: "0 auto" } as const;
const prose = { maxWidth: "var(--w-prose)", margin: "0 auto" } as const;

interface Session {
  n: number; essaySlug: string; title: string; aim: string; summary: string;
  keyScripture: { ref: string; why: string };
  timing: { segment: string; minutes: number }[];
  discussion: { q: string; behind: string }[];
  objections: { objection: string; response: string }[];
  quietRoomQuestion: string; practice: string; closingPrayer: string; reflection: string[];
}
interface Guide {
  slug: string; title: string; subtitle: string; summary: string;
  audience: string; sessionsLabel: string; sessions: Session[];
  facilitatorScript: { open: string; transition: string; close: string };
  cadences: { name: string; plan: string[] }[];
  bibliography: { title: string; author: string; note: string }[];
  furtherReading: string[];
  glossary: { term: string; definition: string }[];
  scriptureIndex: { ref: string; sessions: number[] }[];
  promoKit: { bulletinBlurb: string; pulpitAnnouncement: string; inviteCaption: string };
}

const TABS = ["Leader", "Participant", "Facilitator", "Reference", "Promo"] as const;
type Tab = typeof TABS[number];

const card = { background: "#FFFFFF", border: "1px solid rgba(20,17,12,0.08)", borderTop: "2px solid var(--mustard)", padding: "var(--s-3)", marginBottom: "var(--s-3)" } as const;
const h3 = { fontFamily: "var(--F)", fontSize: "22px", fontWeight: 400, color: "var(--ink)", marginBottom: "10px" } as const;
const lbl = { fontFamily: "var(--U)", fontSize: "11px", fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase" as const, color: "var(--ink-muted)", marginBottom: "6px" };
const body = { fontFamily: "var(--B)", fontSize: "15.5px", lineHeight: 1.7, color: "var(--ink)" } as const;

export default function StudyGuide() {
  const [, params] = useRoute("/studyguides/:slug");
  const slug = params?.slug;
  const [data, setData] = useState<Guide | null>(null);
  const [missing, setMissing] = useState(false);
  const [tab, setTab] = useState<Tab>("Leader");

  useEffect(() => {
    if (!slug) return;
    setData(null); setMissing(false);
    fetch(`/studyguides/${slug}.json`, { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => (d ? setData(d) : setMissing(true)))
      .catch(() => setMissing(true));
  }, [slug]);

  const source = useMemo(() => `toolkit:${slug}`, [slug]);

  return (
    <Layout>
      {data && <SEOMeta title={`${data.title} — Leader's Toolkit`} description={data.subtitle} url={`https://www.livewellbyjamesbell.co/studyguides/${slug}`} />}

      <section style={{ background: "var(--charcoal)", padding: "var(--s-6) var(--s-4) var(--s-5)", color: "var(--bone)" }}>
        <div style={wrap}>
          <div className="eyebrow" style={{ color: "var(--mustard)", marginBottom: "16px" }}>Study Guide · Leader's Toolkit</div>
          <h1 style={{ fontFamily: "var(--F)", fontSize: "clamp(30px, 5vw, 52px)", fontWeight: 400, lineHeight: 1.06, letterSpacing: "-0.025em", marginBottom: "16px", maxWidth: "22ch" }}>{data?.title ?? (missing ? "Not found" : "Loading…")}</h1>
          {data && (
            <>
              <p style={{ fontFamily: "var(--B)", fontSize: "16px", lineHeight: 1.7, color: "rgba(245,240,230,0.8)", maxWidth: "60ch", marginBottom: "8px" }}>{data.audience} · {data.sessionsLabel}</p>
              <div style={{ display: "flex", gap: "12px", flexWrap: "wrap", marginTop: "16px" }}>
                <GatedDownload href={`/downloads/studyguides/${slug}-leader.pdf`} label="Leader's Guide (PDF)" source={source} />
                <GatedDownload href={`/downloads/studyguides/${slug}-participant.pdf`} label="Participant Handout (PDF)" source={source} />
              </div>
            </>
          )}
        </div>
      </section>

      {data && (
        <>
          <section style={{ background: "var(--bone)", padding: "var(--s-4) var(--s-4) 0" }}>
            <div style={wrap}>
              <p style={{ ...body, maxWidth: "68ch", marginBottom: "var(--s-3)" }}>{data.summary}</p>
              <div role="tablist" aria-label="Toolkit sections" style={{ display: "flex", gap: "6px", flexWrap: "wrap", borderBottom: "1px solid rgba(20,17,12,0.12)" }}>
                {TABS.map((t) => (
                  <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}
                    style={{ fontFamily: "var(--U)", fontSize: "13.5px", fontWeight: 600, padding: "10px 14px", minHeight: "44px", cursor: "pointer", border: "none", background: "none", color: tab === t ? "var(--ink)" : "var(--ink-muted)", borderBottom: tab === t ? "2px solid var(--mustard)" : "2px solid transparent" }}>
                    {t === "Leader" ? "Leader's Guide" : t === "Participant" ? "Participant Handout" : t === "Facilitator" ? "Facilitator Script" : t}
                  </button>
                ))}
              </div>
            </div>
          </section>

          <section style={{ background: "var(--bone)", padding: "var(--s-4) var(--s-4) var(--s-6)" }}>
            <div style={wrap}>
              {tab === "Leader" && data.sessions.map((s) => (
                <div key={s.n} style={card}>
                  <div style={lbl}>Session {s.n} · {s.timing.map((t) => `${t.segment} ${t.minutes}m`).join(" · ")}</div>
                  <h3 style={h3}>{s.title}</h3>
                  <p style={{ ...body, fontStyle: "italic", marginBottom: "12px" }}>Aim: {s.aim}</p>
                  <Link href={`/writing/${s.essaySlug}`} style={{ fontFamily: "var(--U)", fontSize: "13px", fontWeight: 600, color: "var(--mustard-text)" }}>Read the essay for this session →</Link>
                  <div style={{ ...lbl, marginTop: "16px" }}>Key Scripture</div>
                  <p style={body}>{s.keyScripture.ref} — {s.keyScripture.why}</p>
                  <div style={{ ...lbl, marginTop: "16px" }}>Discussion</div>
                  {s.discussion.map((d, i) => (
                    <div key={i} style={{ marginBottom: "12px" }}>
                      <p style={{ ...body, fontWeight: 600 }}>{i + 1}. {d.q}</p>
                      <p style={{ ...body, color: "var(--ink-muted)", borderLeft: "2px solid var(--mustard)", paddingLeft: "12px", marginTop: "4px" }}>{d.behind}</p>
                    </div>
                  ))}
                  <div style={{ ...lbl, marginTop: "8px" }}>If the room goes quiet</div>
                  <p style={body}>{s.quietRoomQuestion}</p>
                  <div style={{ ...lbl, marginTop: "16px" }}>Anticipated objections</div>
                  {s.objections.map((o, i) => (
                    <div key={i} style={{ marginBottom: "10px" }}>
                      <p style={{ ...body, fontWeight: 600 }}>“{o.objection}”</p>
                      <p style={{ ...body, color: "var(--ink-muted)" }}>{o.response}</p>
                    </div>
                  ))}
                  <div style={{ ...lbl, marginTop: "8px" }}>Closing prayer</div>
                  <p style={{ ...body, fontFamily: "var(--F)", fontSize: "17px", fontStyle: "italic" }}>{s.closingPrayer}</p>
                </div>
              ))}

              {tab === "Participant" && data.sessions.map((s) => (
                <div key={s.n} style={card}>
                  <div style={lbl}>Session {s.n}</div>
                  <h3 style={h3}>{s.title}</h3>
                  <p style={{ ...body, marginBottom: "12px" }}>{s.summary}</p>
                  <div style={lbl}>Key Scripture</div>
                  <p style={{ ...body, marginBottom: "12px" }}>{s.keyScripture.ref}</p>
                  <div style={lbl}>Reflect</div>
                  {s.reflection.map((r, i) => <p key={i} style={{ ...body, marginBottom: "6px" }}>{i + 1}. {r}</p>)}
                  <div style={{ ...lbl, marginTop: "12px" }}>This week, try this</div>
                  <p style={body}>{s.practice}</p>
                </div>
              ))}

              {tab === "Facilitator" && (
                <div style={{ ...prose }}>
                  <div style={card}>
                    <div style={lbl}>Open (read aloud)</div>
                    <p style={{ ...body, fontFamily: "var(--F)", fontSize: "17px" }}>{data.facilitatorScript.open}</p>
                    <div style={{ ...lbl, marginTop: "16px" }}>Move to application</div>
                    <p style={{ ...body, fontFamily: "var(--F)", fontSize: "17px" }}>{data.facilitatorScript.transition}</p>
                    <div style={{ ...lbl, marginTop: "16px" }}>Close (read aloud)</div>
                    <p style={{ ...body, fontFamily: "var(--F)", fontSize: "17px" }}>{data.facilitatorScript.close}</p>
                  </div>
                  <div style={card}>
                    <div style={lbl}>Three ways to run it</div>
                    {data.cadences.map((c) => (
                      <div key={c.name} style={{ marginBottom: "12px" }}>
                        <p style={{ ...body, fontWeight: 600 }}>{c.name}</p>
                        {c.plan.map((p, i) => <p key={i} style={{ ...body, color: "var(--ink-muted)" }}>{p}</p>)}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {tab === "Reference" && (
                <div style={{ ...prose }}>
                  <div style={card}>
                    <div style={lbl}>Bibliography</div>
                    {data.bibliography.map((b, i) => (
                      <p key={i} style={{ ...body, marginBottom: "8px" }}><span style={{ fontStyle: "italic" }}>{b.title}</span>, {b.author}. <span style={{ color: "var(--ink-muted)" }}>{b.note}</span></p>
                    ))}
                    <div style={{ ...lbl, marginTop: "12px" }}>Further reading</div>
                    {data.furtherReading.map((f, i) => <p key={i} style={{ ...body, marginBottom: "4px" }}>{f}</p>)}
                  </div>
                  <div style={card}>
                    <div style={lbl}>Glossary</div>
                    {data.glossary.map((g, i) => (
                      <p key={i} style={{ ...body, marginBottom: "8px" }}><span style={{ fontWeight: 600 }}>{g.term}.</span> {g.definition}</p>
                    ))}
                  </div>
                  <div style={card}>
                    <div style={lbl}>Scripture index</div>
                    {data.scriptureIndex.map((s, i) => (
                      <p key={i} style={{ ...body, marginBottom: "4px" }}>{s.ref} <span style={{ color: "var(--ink-muted)" }}>(session{s.sessions.length > 1 ? "s" : ""} {s.sessions.join(", ")})</span></p>
                    ))}
                  </div>
                </div>
              )}

              {tab === "Promo" && (
                <div style={{ ...prose }}>
                  <div style={card}>
                    <div style={lbl}>Bulletin blurb</div>
                    <p style={{ ...body, marginBottom: "16px" }}>{data.promoKit.bulletinBlurb}</p>
                    <div style={lbl}>Pulpit announcement</div>
                    <p style={{ ...body, marginBottom: "16px" }}>{data.promoKit.pulpitAnnouncement}</p>
                    <div style={lbl}>Invite caption</div>
                    <p style={body}>{data.promoKit.inviteCaption}</p>
                  </div>
                </div>
              )}
            </div>
          </section>
        </>
      )}
    </Layout>
  );
}
