/**
 * build-pdfs.mjs — every downloadable PDF, built at deploy time (`pnpm pdfs`,
 * run by build:vercel) into client/public/downloads/, plus the manifest the
 * /resources hub reads (client/public/downloads/index.json).
 *
 * What gets built is scripts/pdf-kit/plan.mjs; how it looks is the shared
 * print kit, scripts/pdf-kit/index.mjs (brand fonts embedded, tagged PDF,
 * bookmarks, links, metadata). Output file names for the study guides,
 * context guides and reading paths are unchanged, so existing links hold.
 *
 * Run:  node scripts/build-pdfs.mjs            # everything + manifest
 *       node scripts/build-pdfs.mjs family/    # only files whose path matches
 *
 * Idempotent: identical content yields byte-identical PDFs (fixed dates).
 * Jobs are spread across worker threads, one per core up to four.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Worker } from "node:worker_threads";
import { planDownloads, CATEGORIES, OUT_DIR, ROOT } from "./pdf-kit/plan.mjs";

const RENDER = fileURLToPath(new URL("./pdf-kit/render.mjs", import.meta.url));

function runPool(files, threads) {
  return new Promise((resolve, reject) => {
    const results = [];
    const queue = files.slice();
    let live = 0;
    const next = (w) => {
      const f = queue.shift();
      w.postMessage(f ?? null);
    };
    for (let i = 0; i < threads; i++) {
      live++;
      const w = new Worker(RENDER, { workerData: { worker: true } });
      w.on("message", (m) => {
        if (!m.ready) {
          results.push(m);
          if (!m.ok) console.error(`  FAILED ${m.file}\n${m.error}`);
          else if (process.env.PDF_VERBOSE) console.log(`  ${(m.bytes / 1024).toFixed(1).padStart(7)} KB  ${m.pages.toString().padStart(3)} pp  ${m.file}`);
        }
        next(w);
      });
      w.on("error", reject);
      w.on("exit", () => {
        if (--live === 0) resolve(results);
      });
    }
  });
}

function removeStale(planned) {
  const keep = new Set([...planned, "index.json"]);
  const walk = (dir) => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, e.name);
      if (e.isDirectory()) {
        walk(abs);
        if (!fs.readdirSync(abs).length) fs.rmdirSync(abs);
      } else if (!keep.has(path.relative(OUT_DIR, abs).split(path.sep).join("/"))) {
        fs.rmSync(abs);
      }
    }
  };
  walk(OUT_DIR);
}

async function main() {
  const t0 = Date.now();
  const filter = process.argv[2] || "";
  const jobs = await planDownloads();
  const todo = jobs.filter((j) => j.file.includes(filter));
  const threads = Math.max(1, Math.min(4, os.availableParallelism?.() || os.cpus().length, todo.length));
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const results = await runPool(todo.map((j) => j.file), threads);
  const failed = results.filter((r) => !r.ok);
  if (failed.length) {
    console.error(`build-pdfs: ${failed.length} of ${todo.length} PDFs failed.`);
    process.exit(1);
  }

  const byFile = new Map(results.map((r) => [r.file, r]));
  if (!filter) {
    removeStale(jobs.map((j) => j.file));
    const order = new Map(CATEGORIES.map((c, i) => [c.name, i]));
    const manifest = {
      note: "Generated by scripts/build-pdfs.mjs. Every downloadable PDF, by category.",
      categories: CATEGORIES,
      files: jobs
        .map((j) => {
          const r = byFile.get(j.file);
          const entry = { title: j.title, file: `/downloads/${j.file}`, category: j.category, pages: r.pages, bytes: r.bytes };
          if (j.page) entry.page = j.page;
          if (j.gated) entry.gated = true;
          return entry;
        })
        .sort((a, b) => (order.get(a.category) ?? 99) - (order.get(b.category) ?? 99)),
    };
    fs.writeFileSync(path.join(OUT_DIR, "index.json"), JSON.stringify(manifest, null, 1) + "\n");
  }

  const counts = {};
  let total = 0;
  let pages = 0;
  for (const j of todo) {
    counts[j.category] = (counts[j.category] || 0) + 1;
    total += byFile.get(j.file).bytes;
    pages += byFile.get(j.file).pages;
  }
  for (const [c, n] of Object.entries(counts)) console.log(`  ${String(n).padStart(4)}  ${c}`);
  console.log(
    `\n${todo.length} PDFs, ${pages} pages, ${(total / 1024 / 1024).toFixed(1)} MB in ${((Date.now() - t0) / 1000).toFixed(1)}s ` +
      `on ${threads} thread${threads > 1 ? "s" : ""}${filter ? ` (filter "${filter}", manifest untouched)` : ` -> ${path.relative(ROOT, OUT_DIR)}/index.json`}.`
  );
}

main().catch((err) => {
  console.error("build-pdfs failed:", err);
  process.exit(1);
});
