/**
 * ReadTheBook — the essay→book door in the reader's journey.
 *
 * Looks the essay up in /books/chapters-index.json (generated by
 * scripts/build-chapters-index.mjs from the book manifests — never
 * hand-kept). If the essay is a chapter of a library book, renders a quiet
 * band: the cover, "This essay is chapter N of <book>", and a link into the
 * free reader. Renders nothing when the essay isn't in a book or while the
 * index loads, so it never blocks or shifts the page.
 */
import { useEffect, useState } from "react";
import { Link } from "wouter";

interface ChapterRef {
  book: string;
  bookTitle: string;
  pillar?: string;
  chapter: number;
  chapters: number;
  cover?: string | null;
}

// One fetch per session, shared across every essay page.
let indexPromise: Promise<Record<string, ChapterRef>> | null = null;
function loadIndex(): Promise<Record<string, ChapterRef>> {
  indexPromise ??= fetch("/books/chapters-index.json")
    .then((r) => (r.ok ? r.json() : {}))
    .catch(() => ({}));
  return indexPromise;
}

export function ReadTheBook({ slug }: { slug: string }) {
  const [ref, setRef] = useState<ChapterRef | null>(null);
  useEffect(() => {
    let live = true;
    loadIndex().then((idx) => { if (live) setRef(idx[slug] ?? null); });
    return () => { live = false; };
  }, [slug]);

  if (!ref) return null;

  return (
    <aside style={{ maxWidth: "var(--w-prose)", margin: "var(--s-5) auto 0", border: "1px solid var(--border)", background: "var(--card)", display: "flex", alignItems: "stretch", overflow: "hidden" }}>
      {ref.cover && (
        <Link href={`/read/${ref.book}`} style={{ flex: "0 0 92px", display: "block" }}>
          <img
            src={ref.cover}
            alt={`${ref.bookTitle} — book cover`}
            loading="lazy"
            width={800}
            height={1200}
            style={{ width: "92px", height: "100%", objectFit: "cover", display: "block", background: "var(--charcoal)" }}
          />
        </Link>
      )}
      <div style={{ padding: "18px 20px", display: "flex", flexDirection: "column", justifyContent: "center", gap: "6px", minWidth: 0 }}>
        <div className="eyebrow" style={{ color: "var(--mustard-text)" }}>Keep reading — free</div>
        <div style={{ fontFamily: "var(--F)", fontSize: "19px", lineHeight: 1.25, color: "var(--ink)" }}>
          This essay is chapter {ref.chapter} of <em>{ref.bookTitle}</em>.
        </div>
        <Link href={`/read/${ref.book}`} style={{ fontFamily: "var(--U)", fontSize: "12.5px", fontWeight: 600, color: "var(--mustard-text)", textDecoration: "none" }}>
          Read the whole book — {ref.chapters} chapters →
        </Link>
      </div>
    </aside>
  );
}
